// src/pages/QnA.tsx
import React, { useState } from 'react';

type Question = {
  question: string;
    answer: string;
    };

    const faqData: Question[] = [
      {
          question: "តើគេហទំព័រនេះជួយកសិករយ៉ាងដូចម្តេច?",
              answer:
                    "យើងផ្តល់ព័ត៌មានអំពីដំណាំសំខាន់ៗ បច្ចេកទេសដាំដុះ ទីផ្សារ និងធនធានឌីជីថល (ដូចជា Tonle Sap App, Chamka App) ដើម្បីជួយកសិករបង្កើនផលិតភាព និងចំណូល។ អ្នកអាចសួរសំណួរបន្ថែមតាមទំនាក់ទំនងបានផងដែរ។",
                      },
                        {
                            question: "តើខ្ញុំអាចទិញគ្រាប់ពូជ ឬជីពីគេហទំព័រនេះបានទេ?",
                                answer:
                                      "បច្ចុប្បន្នយើងមិនទាន់មានប្រព័ន្ធលក់ផ្ទាល់ទេ ប៉ុន្តែយើងណែនាំប្រភពគួរទុកចិត្ត និងភ្ជាប់ទៅកាន់អ្នកផ្គត់ផ្គង់ ឬកម្មវិធីដែលមានសេវាលក់ (ឧ. Tonle Sap App ឬ កសិករក្នុងស្រុក)។ សូមទាក់ទងមកយើងសម្រាប់ការណែនាំបន្ថែម។",
                                        },
                                          {
                                              question: "តើដាំស្រូវវស្សាត្រូវការជីប៉ុន្មាន?",
                                                  answer:
                                                        "ជាទូទៅ ក្នុងមួយហិកតា គេប្រើជីអ៊ុយរ៉េ ៥០–៨០ គីឡូក្រាម ជីផូស្វ័រ (DAP) ៥០–៧០ គីឡូក្រាម និងជីប៉ូតាស (KCl) ៣០–៥០ គីឡូក្រាម អាស្រ័យលើគុណភាពដី។ ប្រើជីធម្មជាតិ (ជីកំប៉ុស) រួមផ្សំអាចកាត់បន្ថយការប្រើប្រាស់ជីគីមីបាន។ សូមពិគ្រោះជាមួយមន្ត្រីកសិកម្មក្នុងមូលដ្ឋាន។",
                                                          },
                                                            {
                                                                question: "តើមានកម្មវិធីណាដែលផ្តល់ជំនួយដល់កសិករដោយឥតគិតថ្លៃ?",
                                                                    answer:
                                                                          "មានកម្មវិធីជាច្រើនដូចជា ASPIRE, គម្រោង CHAIN, និងកម្មវិធីពីក្រសួងកសិកម្ម រុក្ខាប្រមាញ់ និងនេសាទ (MAFF) ដែលផ្តល់គ្រាប់ពូជ ជី បច្ចេកទេស និងបណ្តុះបណ្តាលដោយឥតគិតថ្លៃ ឬតម្លៃទាប។ សូមទាក់ទងមន្ត្រីកសិកម្មឃុំ/សង្កាត់ ឬចុះឈ្មោះតាមកម្មវិធីផ្លូវការ។",
                                                                            },
                                                                              {
                                                                                  question: "តើខ្ញុំអាចចែករំលែករូបភាព ឬបទពិសោធន៍របស់ខ្ញុំបានទេ?",
                                                                                      answer:
                                                                                            "បានហើយ! សូមផ្ញើរូបភាព វីដេអូខ្លី ឬរឿងរ៉ាវរបស់អ្នកមកតាមទំនាក់ទំនង (អ៊ីមែល ឬ Messenger)។ យើងនឹងពិចារណាបង្ហាញនៅក្នុងផ្នែក “រឿងរ៉ាវ” ដើម្បីជួយផ្សព្វផ្សាយដល់កសិករដទៃទៀត។",
                                                                                              },
                                                                                                {
                                                                                                    question: "តើគេហទំព័រនេះឥតគិតថ្លៃទេ?",
                                                                                                        answer:
                                                                                                              "បាទ/ចាស គេហទំព័រនេះឥតគិតថ្លៃទាំងស្រុងសម្រាប់ការប្រើប្រាស់ អានព័ត៌មាន និងសួរសំណួរ។ យើងមិនលក់ផលិតផលផ្ទាល់ទេ ប៉ុន្តែផ្តល់ព័ត៌មាន និងភ្ជាប់ទៅកាន់ប្រភពជឿទុកចិត្ត។",
                                                                                                                },
                                                                                                                ];

                                                                                                                const QnAPage: React.FC = () => {
                                                                                                                  const [openIndex, setOpenIndex] = useState<number | null>(null);

                                                                                                                    const toggleAccordion = (index: number) => {
                                                                                                                        setOpenIndex(openIndex === index ? null : index);
                                                                                                                          };

                                                                                                                            return (
                                                                                                                                <div className="min-h-screen bg-gray-50">
                                                                                                                                      {/* Header / Hero */}
                                                                                                                                            <div className="bg-gradient-to-r from-green-700 to-green-900 text-white">
                                                                                                                                                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16 text-center">
                                                                                                                                                              <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-4">
                                                                                                                                                                          សំណួរ និងចម្លើយ
                                                                                                                                                                                    </h1>
                                                                                                                                                                                              <p className="text-lg md:text-xl max-w-3xl mx-auto opacity-90">
                                                                                                                                                                                                          សំណួរញឹកញាប់បំផុតពីកសិករ និងអ្នកចាប់អារម្មណ៍លើកសិកម្មស្រុកកំណើត
                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                        {/* Main QnA Content */}
                                                                                                                                                                                                                                              <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12">
                                                                                                                                                                                                                                                      <div className="space-y-4">
                                                                                                                                                                                                                                                                {faqData.map((item, index) => (
                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                          key={index}
                                                                                                                                                                                                                                                                                                        className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden"
                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                  onClick={() => toggleAccordion(index)}
                                                                                                                                                                                                                                                                                                                                                                  className="w-full px-6 py-5 text-left flex justify-between items-center hover:bg-gray-50 transition-colors focus:outline-none"
                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-lg font-medium text-gray-800">
                                                                                                                                                                                                                                                                                                                                                                                                                  {item.question}
                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-2xl text-green-600 ml-4 flex-shrink-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {openIndex === index ? '−' : '+'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className={`px-6 pb-5 transition-all duration-300 ease-in-out overflow-hidden ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  openIndex === index ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-700 leading-relaxed">{item.answer}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Still have questions? */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-16 text-center bg-white p-8 rounded-2xl shadow border border-gray-200">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3 className="text-2xl font-bold text-green-800 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  នៅមានសំណួរបន្ថែមទៀត?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-gray-700 mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  សូមទាក់ទងមកយើងដោយផ្ទាល់ យើងរីករាយជួយឆ្លើយសំណួររបស់អ្នក!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="/contact"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            inline-block 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          px-8 py-4 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bg-green-600 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      hover:bg-green-700 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text-white 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  font-medium 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text-lg 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rounded-lg 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            shadow-md 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          transition-all 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        duration-300
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          សួរសំណួរឥឡូវ
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default QnAPage;